set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let vundle manage vundle, required
Plugin 'VundleVim/Vundle.vim'

" plugins
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-unimpaired'
Plugin 'airblade/vim-rooter'
Plugin 'airblade/vim-gitgutter'
Plugin 'vim-syntastic/syntastic'
Plugin 'Shougo/denite.nvim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'Shougo/deoplete.nvim'
Plugin 'majutsushi/tagbar'
Plugin 'bling/vim-airline'
Plugin 'bling/vim-bufferline'
Plugin 'sjl/gundo.vim'

call vundle#end()            " required
filetype plugin indent on    " required

set number
syntax on
set autoread
set ruler
set encoding=utf8
set showcmd

" whitespace
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·
set backspace=indent,eol,start
set smartindent
set autoindent

" searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*

" status bar
set laststatus=2

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" use modeline overrides
set modeline
set modelines=10

set cursorline

" no save backup by .swp
set nowb
set noswapfile
set noar
set nobackup
set nowritebackup

" turn of paste indenting
set paste

" color scheme
set t_Co=256
colorscheme zenburn

" toggle search highlighting
nmap <leader>hs :set hlsearch! hlsearch?<CR>

" splits
nmap <C-w>32 :vertical resize 32<CR>

" navigate buggers and tabs
nmap <F12> :bnext<CR>
nmap <S-F12> :bprevious<CR>

nmap <F8> :TagbarToggle<CR>

nnoremap <F2> :GundoToggle<CR>

nnoremap <leader><leader> <C-^>
